SELECT datname FROM pg_database WHERE datistemplate = true;
SELECT datname FROM pg_database WHERE datistemplate = true AND datallowconn = true;
SELECT datname FROM pg_database WHERE datistemplate = false;
SELECT datname FROM pg_database WHERE datistemplate = false AND datconnlimit = -1;
SELECT spcname, spcoptions FROM pg_tablespace;
SELECT extname, extversion FROM pg_extension;
SELECT name,setting FROM pg_settings WHERE name = 'listen_addresses' AND setting = '*';
SELECT name,setting FROM pg_settings WHERE name = 'port';
SELECT name,setting FROM pg_settings WHERE name = 'port' AND setting = '5432';
SELECT name,setting FROM pg_settings WHERE name = 'max_connections';
SELECT name,setting FROM pg_settings WHERE name = 'superuser_reserved_connections';
SELECT name,setting FROM pg_settings WHERE name = 'unix_socket_group';
SELECT name,setting FROM pg_settings WHERE name = 'unix_socket_permissions';
SELECT name,setting FROM pg_settings WHERE name = 'bonjour' AND setting != 'off';
SELECT name,setting FROM pg_settings WHERE name = 'allow_system_table_mods' AND setting != 'off';
SELECT name,setting FROM pg_settings WHERE name = 'authentication_timeout';
SELECT name,setting FROM pg_settings WHERE name = 'ssl' AND setting != 'on';
SELECT name,setting FROM pg_settings WHERE name = 'ssl_ciphers';
SELECT name,setting FROM pg_settings WHERE name = 'ssl_renegotiation_limit';
SELECT name,setting FROM pg_settings WHERE name = 'password_encryption' AND setting != 'on';
SELECT name,setting FROM pg_settings WHERE name = 'backslash_quote';
SELECT name,setting FROM pg_settings WHERE name = 'log_destination' AND setting NOT LIKE '%syslog%';
SELECT name,setting FROM pg_settings WHERE name = 'syslog_facility' AND setting != 'local0';
SELECT name,setting FROM pg_settings WHERE name = 'syslog_facility' AND setting != '{SYSLOG_FACILITY}';
SELECT name,setting FROM pg_settings WHERE name = 'syslog_ident' AND setting != 'postgres';
SELECT name,setting FROM pg_settings WHERE name = 'syslog_ident' AND setting != '{SYSLOG_IDENT}';
SELECT name,setting FROM pg_settings WHERE name = 'logging_collector' AND setting != 'on';
SELECT name,setting FROM pg_settings WHERE name = 'log_directory' AND setting != 'pg_log';
SELECT name,setting FROM pg_settings WHERE name = 'log_directory' AND setting != '{LOG_DIRECTORY}';
SELECT name,setting FROM pg_settings WHERE name = 'log_filename' AND setting != 'postgresql-%a.log';
SELECT name,setting FROM pg_settings WHERE name = 'log_filename' AND setting != '{LOG_FILE}';
SELECT name,setting FROM pg_settings WHERE name = 'log_file_mode' AND setting != '0600';
SELECT name,setting FROM pg_settings WHERE name = 'log_truncate_on_rotation' AND setting != 'off';
SELECT name,setting FROM pg_settings WHERE name = 'log_rotation_age' AND setting > '1440';
SELECT name,setting FROM pg_settings WHERE name = 'log_rotation_age' AND setting > '{LOG_AGE}';
SELECT name,setting FROM pg_settings WHERE name = 'log_rotation_size' AND setting > '0';
SELECT name,setting FROM pg_settings WHERE name = 'log_rotation_size' AND setting > '{LOG_SIZE}';
SELECT name,setting FROM pg_settings WHERE name = 'client_min_messages';
SELECT name,setting FROM pg_settings WHERE name = 'log_min_messages';
SELECT name,setting FROM pg_settings WHERE name = 'log_min_error_statement';
SELECT name,setting FROM pg_settings WHERE name = 'log_connections' AND setting != 'on';
SELECT name,setting FROM pg_settings WHERE name = 'log_disconnections' AND setting != 'on';
SELECT name,setting FROM pg_settings WHERE name = 'log_error_verbosity';
SELECT name,setting FROM pg_settings WHERE name = 'log_hostname' AND setting != 'off';
SELECT name,setting FROM pg_settings WHERE name = 'log_statement';
SELECT name,setting FROM pg_settings WHERE name = 'wal_level';
SELECT name,setting FROM pg_settings WHERE name = 'archive_mode' AND setting != 'on';
SELECT rolname FROM pg_roles;
SELECT rolname FROM pg_roles WHERE rolcanlogin = true;
SELECT rolname FROM pg_roles WHERE rolcanlogin = true AND rolpassword IS NULL;
SELECT rolname FROM pg_roles WHERE rolsuper = true;
SELECT rolname FROM pg_roles WHERE rolcreaterole = true AND rolsuper = false;
SELECT rolname FROM pg_roles WHERE rolcreatedb = true AND rolsuper = false;
SELECT rolname,rolvaliduntil FROM pg_roles WHERE rolsuper = false AND rolvaliduntil IS NULL;
SELECT rolname,rolconnlimit FROM pg_roles WHERE rolsuper = false AND rolconnlimit = -1;
SELECT usename FROM pg_shadow WHERE passwd IS NULL;
SELECT usename FROM pg_shadow WHERE passwd NOT LIKE 'md5%';
SELECT usename FROM pg_shadow WHERE passwd NOT LIKE 'md5%' AND CHAR_LENGTH(passwd) < 8;
SELECT groname from pg_group join pg_authid on (pg_group.groname=pg_authid.rolname) WHERE rolsuper = true;
SELECT groname,usename from pg_group join pg_authid ON (pg_group.groname=pg_authid.rolname) join pg_auth_members ON (pg_group.grosysid=pg_auth_members.roleid) join pg_user ON (pg_auth_members.member=pg_user.usesysid) WHERE rolsuper = true;
SELECT CAST(has_schema_privilege('public','public','CREATE') AS TEXT);
SELECT relname,relacl FROM pg_class WHERE relname = 'pg_authid' AND CAST(relacl AS TEXT) LIKE '%,=%}';
SELECT relname,relacl FROM pg_class WHERE CAST(relacl AS TEXT) LIKE '%=%*%/%';
SELECT relname,relacl FROM pg_class WHERE CAST(relacl AS TEXT) LIKE '%,=%}' OR CAST(relacl AS TEXT) LIKE '{=%}';
SELECT label FROM pg_seclabels WHERE label IS NOT NULL;
SELECT objname,provider,label FROM pg_seclabels;
